backend:
  name: github
  repo: https://github.com/ohadpr/ohadpr.com.git
  branch: master # Branch to update (master by default)

media_folder: "img/uploads" # Folder where user uploaded files should go

collections: # A list of collections the CMS should be able to edit
  - name: "index"
    label: "index"
    file: "index.html"
