backend:
  name: github
  repo: https://github.com/ohadpr/ohadpr.com
  branch: master # Branch to update (master by default)

media_folder: "img/uploads" # Folder where user uploaded files should go

collections: # A list of collections the CMS should be able to edit
  - name: "files"
    label: "files"
    files:
      - name: "index.html"
        label: "index.html"
        file: "index.html"
